version: '3.3'

services:
  vet_app_db:
    container_name: vet_app_db
    image: postgres:latest
    restart: always
    ports:
      - '54321:54321'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  vet_app:
    container_name: vet_app
    build: ./build/
    command: /usr/src/app/main/start.sh
    depends_on:
      - vet_app_db
    volumes:
      - ./app:/usr/src/app
    ports:
      - '3800:8000'
#    volumes:
#      - postgres:/var/lib/postgresql/data
